# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaiZhouEPApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TaiZhouEPApp

  target 'TaiZhouEPAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaiZhouEPAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SDWebImage', '~> 4.4.2'
pod 'AFNetworking', '~> 3.2.1'
pod 'HBDNavigationBar', '~> 1.3.2'
pod 'FMDB', '~> 2.7.5'
pod 'Masonry', '~> 1.1.0'
pod 'CocoaAsyncSocket'
pod 'SDWebImage'

end
